version: "3"

services:
  frontend:
    container_name: frontend
    restart: always
    build: ./frontend
    ports:
      - "8080:80"

  # backend:
  #   container_name: backend
  #   restart: always
  #   build: ./backend
