server:
  port: 8080
  shutdown: graceful



spring:
  profiles:
    include: credential, local
  datasource:
    # docker
    #url: jdbc:mysql://host.docker.internal:3306/blogbooster?serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
    # host
    url: jdbc:mysql://localhost:3306/blogbooster?serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    allow-bean-definition-overriding: true
  jpa:
    properties:
      hibernate:
        format_sql:true
    show-sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true #true이면 flyway_schema_history테이블을 생성해줌
    locations: classpath:/db/migration
    baseline-version: 0 #baseline을 설정해놓으면 해당 숫자보다 큰 버전의sql만 수행함
                        #ex) 4일경우 V5 부터 수행함.
                        #migration sql은 resourse/db/migration/에 위치함

logging:
  level:
    level:
      org.hibernate.SQL: DEBUG
    com:
      snl:
        blogBooster: DEBUG
    org:
      springframework:
        web:
          servlet:
            DispatcherServlet: DEBUG

# MyBatis
# mapper.xml 위치 지정
mybatis:
  mapper-locations: classpath:mapper/*.xml

# model 프로퍼티 camel case 설정
mybatis.configuration.map-underscore-to-camel-case: true


